-- NB: NoImplicitPrelude is active from cabal common-options.
--
-- Artifact generators that consume a 'SysDoc' (or legacy 'SystemSpec').
-- None of these functions are in the synthesis path.
module Isacle.System.Generate
    ( -- * SysDoc-based generators (primary path)
      sysExtractMemoryMap
    , sysGenCHeader
    , sysGenLinkerScript
      -- * Legacy SystemSpec-based generators
    , extractMemoryMap
    , genCHeader
    , genLinkerScript
    ) where

import Prelude
import Data.Char (toUpper)
import Data.List (intercalate, sortBy)
import Data.Ord (comparing)
import Data.Word (Word8, Word32)
import Numeric (showHex)

import Isacle.System.Spec
import Isacle.System.SystemDSL  (SysDoc(..), BusSection(..), PeriphEntry(..))
import Isacle.System.Periph  (PeriphSpec(..), FieldSpec(..), RegAccess(..), RegWidth(..), BitField(..), specSize)
import Hdl.Net                (Repr(..))

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

hex32 :: Word32 -> String
hex32 w = "0x" ++ pad (showHex w "")
  where pad s = replicate (8 - length s) '0' ++ s

padRight :: Int -> String -> String
padRight n s = s ++ replicate (max 0 (n - length s)) ' '

compBase :: ComponentSpec -> Word32
compBase (SpecROM b _ _)    = b
compBase (SpecRAM b _ _ _)  = b
compBase (SpecPeriph b _ _ _) = b
compBase _                  = maxBound

isMem :: ComponentSpec -> Bool
isMem SpecROM{}    = True
isMem SpecRAM{}    = True
isMem SpecPeriph{} = True
isMem _            = False

isPort :: ComponentSpec -> Bool
isPort SpecPort{} = True
isPort _          = False

-- ---------------------------------------------------------------------------
-- extractMemoryMap
-- ---------------------------------------------------------------------------

-- | Human-readable memory map table.
--
-- Example output:
--
-- > MEMORY MAP
-- > ==========
-- > Base         End          Size         Name
-- > ------------------------------------------------------------
-- > 0x00000000   0x00001FFF   0x00002000   code (ROM)
-- > 0x00001000   0x000017FF   0x00000800   ram  (RAM)
-- > 0x00000300   0x00000307   0x00000008   uart (peripheral)
-- > 0x00000500   0x0000050F   0x00000010   gpio (peripheral)
-- >
-- > PORTS
-- > =====
-- > uart_rx              PIn  (1-bit)
-- > uart_tx              POut (1-bit)
-- >
-- > CPU: AVR clavr
extractMemoryMap :: SystemSpec -> String
extractMemoryMap spec = unlines $ concat
    [ header
    , map renderMem (sortBy (comparing compBase) memComps)
    , portSection
    , cpuSection
    ]
  where
    comps    = ssComponents spec
    memComps = filter isMem comps
    portComps = filter isPort comps
    cpuNames  = [n | SpecCPU n <- comps]

    col = 13
    header =
        [ "MEMORY MAP"
        , "=========="
        , padRight col "Base" ++ padRight col "End" ++ padRight col "Size" ++ "Name"
        , replicate 65 '-'
        ]

    renderMem (SpecROM b sz n) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (ROM)"
    renderMem (SpecRAM b sz n _) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (RAM)"
    renderMem (SpecPeriph b sz n _) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (peripheral)"
    renderMem _ = ""

    portSection
        | null portComps = []
        | otherwise = "" : "PORTS" : "=====" : map renderPort portComps

    renderPort (SpecPort n d w) =
        padRight 21 n ++ padRight 6 (show d) ++ "(" ++ showWidth w ++ ")"
    renderPort _ = ""

    showWidth PW1  = "1-bit"
    showWidth PW8  = "8-bit"
    showWidth PW16 = "16-bit"
    showWidth PW32 = "32-bit"

    cpuSection
        | null cpuNames = []
        | otherwise     = ["", "CPU: " ++ intercalate ", " cpuNames]

-- ---------------------------------------------------------------------------
-- genCHeader
-- ---------------------------------------------------------------------------

-- | Generate a C header defining @BASE@ and @SIZE@ macros for every
--   memory-mapped component.
--
-- @guardName@ becomes the include guard (converted to upper-case, @_H@ appended).
--
-- Example (@guardName = "memmap"@):
--
-- > /* Auto-generated by ISACLE */
-- > #ifndef MEMMAP_H
-- > #define MEMMAP_H
-- >
-- > #define CODE_BASE  0x00000000UL
-- > #define CODE_SIZE  0x00002000UL
-- > #define RAM_BASE   0x00001000UL
-- > ...
-- > #endif /* MEMMAP_H */
genCHeader :: String -> SystemSpec -> String
genCHeader guardName spec = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "#ifndef " ++ guard
    , "#define " ++ guard
    , ""
    ]
    ++ concatMap renderComp memComps
    ++
    [ ""
    , "#endif /* " ++ guard ++ " */"
    ]
  where
    guard    = map toUpper guardName ++ "_H"
    memComps = filter isMem (ssComponents spec)
    up       = map toUpper
    hexUL w  = "0x" ++ map toUpper (showHex w "") ++ "UL"

    renderComp (SpecROM b sz n) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp (SpecRAM b sz n _) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp (SpecPeriph b sz n _) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp _ = []

-- ---------------------------------------------------------------------------
-- genLinkerScript
-- ---------------------------------------------------------------------------

-- | Generate a GNU LD linker script with MEMORY and SECTIONS directives.
--
-- All 'SpecROM' components become @(rx)@ regions; all 'SpecRAM' components
-- become @(rwx)@ regions.  Standard ELF sections are mapped to the first ROM
-- (read-only) and first RAM (writable) found in the spec.
--
-- Example:
--
-- > MEMORY {
-- >   code (rx)  : ORIGIN = 0x0, LENGTH = 0x2000
-- >   ram  (rwx) : ORIGIN = 0x1000, LENGTH = 0x800
-- > }
-- >
-- > SECTIONS {
-- >   .text   : { *(.text*)   } > code
-- >   .rodata : { *(.rodata*) } > code
-- >   .data   : { *(.data*)   } > ram AT > code
-- >   .bss    : { *(.bss*)    } > ram
-- > }
genLinkerScript :: SystemSpec -> String
genLinkerScript spec = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "MEMORY {"
    ]
    ++ map renderRegion (sortBy (comparing compBase) (romComps ++ ramComps))
    ++
    [ "}"
    , ""
    , "SECTIONS {"
    , "  .text   : { *(.text*)   } > " ++ romReg
    , "  .rodata : { *(.rodata*) } > " ++ romReg
    , "  .data   : { *(.data*)   } > " ++ ramReg ++ " AT > " ++ romReg
    , "  .bss    : { *(.bss*)    } > " ++ ramReg
    , "}"
    ]
  where
    comps   = ssComponents spec
    romComps = [c | c@SpecROM{} <- comps]
    ramComps = [c | c@SpecRAM{} <- comps]

    romReg = case romComps of (SpecROM _ _ n : _) -> n; _ -> "rom"
    ramReg = case ramComps of (SpecRAM _ _ n _ : _) -> n; _ -> "ram"

    hexLen w = "0x" ++ showHex w ""

    renderRegion (SpecROM b sz n) =
        "  " ++ padRight 8 n ++ "(rx)  : ORIGIN = " ++ hexLen b ++ ", LENGTH = " ++ hexLen sz
    renderRegion (SpecRAM b sz n _) =
        "  " ++ padRight 8 n ++ "(rwx) : ORIGIN = " ++ hexLen b ++ ", LENGTH = " ++ hexLen sz
    renderRegion _ = ""

-- ===========================================================================
-- SysDoc-based generators (primary path)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Helpers (shared)
-- ---------------------------------------------------------------------------

allEntries :: SysDoc -> [(BusSection, PeriphEntry)]
allEntries doc = [(bs, pe) | bs <- sdBuses doc, pe <- bsEntries bs]

-- ---------------------------------------------------------------------------
-- sysExtractMemoryMap
-- ---------------------------------------------------------------------------

-- | Human-readable memory map table derived from a 'SysDoc'.
--
-- Example:
--
-- > MEMORY MAP
-- > ==========
-- > Bus       Name              Base         End          Size
-- > ---------------------------------------------------------------
-- > databus   uart0             0x00000100   0x00000102   0x00000003
-- > databus   gpio0             0x00000300   0x00000301   0x00000002
-- >
-- > CPU: cpu0 (AVR8)
-- >
-- > REGISTERS
-- > =========
-- > uart0 (databus @ 0x00000100)
-- >   +0x00  RW  UDR   TX write / RX read
-- >   +0x01  RO  USR   Status
-- >   +0x02  RW  UBRR  Baud rate divisor
sysExtractMemoryMap :: SysDoc -> String
sysExtractMemoryMap doc = unlines $ concat
    [ mapHeader
    , sortBy (comparing (\(_,pe) -> peBase pe)) (allEntries doc)
      >>= \(bs, pe) -> [renderRow bs pe]
    , cpuSection
    , regSection
    ]
  where
    col = 13

    mapHeader =
        [ "MEMORY MAP"
        , "=========="
        , padRight 10 "Bus" ++ padRight 18 "Name"
          ++ padRight col "Base" ++ padRight col "End" ++ "Size"
        , replicate 65 '-'
        ]

    sz pe   = specSize (peSpec pe)
    base pe = peBase pe

    renderRow bs pe =
        padRight 10 (bsName bs) ++ padRight 18 (peName pe)
        ++ padRight col (hex32 (base pe))
        ++ padRight col (hex32 (base pe + sz pe - 1))
        ++ hex32 (sz pe)

    cpuSection
        | null (sdCPUs doc) = []
        | otherwise = ["", "CPU: " ++ intercalate ", " (sdCPUs doc)]

    regSection
        | null (allEntries doc) = []
        | otherwise = "" : "REGISTERS" : "=========" : concatMap renderPeriph (allEntries doc)

    renderPeriph (bs, pe) =
        (peName pe ++ " (" ++ bsName bs ++ " @ " ++ hex32 (peBase pe) ++ ")")
        : map renderField (psFields (peSpec pe))
        ++ [""]

    renderField f =
        "  +" ++ hex8 (fieldOffset f) ++ "  "
        ++ padRight 4 (renderAccess (fieldAccess f)) ++ "  "
        ++ padRight 8 (fieldName f) ++ "  "
        ++ fieldDesc f

    renderAccess ReadOnly  = "RO"
    renderAccess ReadWrite = "RW"
    renderAccess WriteOnly = "WO"

    hex8 :: Word8 -> String
    hex8 b = "0x" ++ (if b < 16 then "0" else "") ++ showHex b ""

-- ---------------------------------------------------------------------------
-- sysGenCHeader
-- ---------------------------------------------------------------------------

-- | Generate a C header from a 'SysDoc'.
--
-- Produces @NAME_BASE@ and @NAME_SIZE@ macros for every peripheral,
-- plus per-register @NAME_REG@ offset macros.
--
-- Example (@guardName = "memmap"@):
--
-- > /* Auto-generated by ISACLE */
-- > #ifndef MEMMAP_H
-- > #define MEMMAP_H
-- >
-- > /* databus */
-- > #define UART0_BASE  0x100UL
-- > #define UART0_SIZE  0x3UL
-- > #define UART0_UDR   0x0UL
-- > #define UART0_USR   0x1UL
-- > #define UART0_UBRR  0x2UL
-- >
-- > #endif /* MEMMAP_H */
sysGenCHeader :: String -> SysDoc -> String
sysGenCHeader guardName doc = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "#ifndef " ++ guard
    , "#define " ++ guard
    ]
    ++ concatMap renderBus (sdBuses doc)
    ++
    [ ""
    , "#endif /* " ++ guard ++ " */"
    ]
  where
    guard   = map toUpper guardName ++ "_H"
    up      = map toUpper
    hexUL w = "0x" ++ map toUpper (showHex w "") ++ "UL"

    renderBus bs =
        ("" : ("/* " ++ bsName bs ++ " */") : concatMap (renderEntry (bsName bs)) (bsEntries bs))

    renderEntry _busName pe =
        let prefix = up (peName pe)
            regs   = concatMap (renderReg prefix) (psFields (peSpec pe))
        in [ "#define " ++ prefix ++ "_BASE  " ++ hexUL (peBase pe)
           , "#define " ++ prefix ++ "_SIZE  " ++ hexUL (specSize (peSpec pe))
           ]
           ++ regs

    -- A register's offset macro (annotated with the C type the bits should be
    -- read as, from its 'Repr'), followed by one _BIT macro per bit-field.
    renderReg prefix f =
        let rname = prefix ++ "_" ++ up (fieldName f)
        in ( "#define " ++ rname ++ "  " ++ hexUL (fromIntegral (fieldOffset f) :: Word32)
                 ++ "  /* " ++ cType (fieldRepr f) (fieldWidth f) ++ " */" )
           : [ "#define " ++ rname ++ "_" ++ up (bfName b) ++ "_BIT  " ++ show (bfLoBit b)
             | b <- fieldBitFields f ]

    -- Map representation + width to a stdint C type.
    cType repr rw =
        let signed = case repr of { RSigned -> "int"; _ -> "uint" }
            bits   = case rw of { RW8 -> "8"; RW16 -> "16"; RW32 -> "32" }
        in signed ++ bits ++ "_t"

-- ---------------------------------------------------------------------------
-- sysGenLinkerScript
-- ---------------------------------------------------------------------------

-- | Generate a GNU LD linker script stub from a 'SysDoc'.
-- Emits MEMORY regions for RAM/ROM entries if present; otherwise emits
-- placeholder regions based on bus map addresses.
sysGenLinkerScript :: SysDoc -> String
sysGenLinkerScript doc = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "/* Peripheral address map */"
    , "MEMORY {"
    ]
    ++ map renderPeriph (allEntries doc)
    ++
    [ "}"
    ]
  where
    hexLen w = "0x" ++ showHex w ""

    renderPeriph (_, pe) =
        "  " ++ padRight 16 (peName pe)
        ++ "(rw) : ORIGIN = " ++ hexLen (peBase pe)
        ++ ", LENGTH = " ++ hexLen (specSize (peSpec pe))
